### PR TITLE
Fixed removal of cloudkeeper attributes on saved templates and images

### LINKED ISSUE #28: Remove CLOUDKEEPER* and VMCATCHER* attributes from templates on 'save'
Remove:
* Attributes in `Template` after cloning
* Attributes in `Image` after cloning (for each `DISK/IMAGE_ID` in `Template`)

### PR DESCRIPTION
**Pull request by arax**
Fixes #28 + minor changes below.

## Changes
* Minor version bump on rOCCI-core (attached for convenience)
* Fixed ONe -> OCCI state handling (to enable the right actions)
* Refactored XPATH-based element counting used by various actions
* Fixed a bug in `bin/oneresource` breaking tests

### CODE REVIEW

File: app/jobs/opennebula/compute_action_job.rb [hunk 1]
```diff
@@ -5,35 +5,91 @@ class ComputeActionJob < OpennebulaActionJob
...
+    def job_cleanup!
+      super
+      return unless @_cleanup_templates
+
+      logger.debug { "Running after-fail cleanup on #{@_cleanup_templates.inspect}" }
+      @_cleanup_templates.each do |tpl|
+        logger.warn "Cleaning up TEMPLATE##{tpl} after save action failed"
+        begin
+          handle { template(tpl).delete(true) }
+        rescue StandardError => ex
```
Comment (amarthadan) [inline app/jobs/opennebula/compute_action_job.rb:26]: Are you sure you should be catching `StandardError`?

Comment (arax) [reply app/jobs/opennebula/compute_action_job.rb:26]: Yes.

**Review by amarthadan — APPROVED** [review]
🌮
